#pragma once
static const char PANEL[] PROGMEM=R"HTML(<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#111827"><title>A22 Expresso • Botizin</title><style>
*{box-sizing:border-box}body{margin:0;background:#0b1220;color:#e5eefc;font:16px system-ui,sans-serif}main{max-width:600px;margin:auto;padding:24px 18px}h1{font-size:30px;margin-bottom:6px}p{line-height:1.5;color:#a9bbd4}.card{padding:18px;background:#17243a;border:1px solid #2c405d;border-radius:18px;margin-top:18px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}button{border:1px solid #405777;border-radius:12px;background:#233b5c;color:white;padding:16px;font:inherit;touch-action:manipulation}button:active{background:#35619a}button:disabled{opacity:.5}.wide{width:100%;margin-top:12px}#state{min-height:48px;color:#a7f3d0}small{color:#a9bbd4}#metrics{font-size:14px;line-height:1.7;white-space:pre-line}</style></head><body><main>
<h1>A22 Expresso</h1><p>Seu celular conversa diretamente com os olhos do Botizin, pelo Wi-Fi local.</p>
<div class="card"><strong id="connection">Conferindo a placa…</strong><div id="metrics"></div></div>
<div class="card"><div class="grid">
<button data-mood="normal">Normal</button><button data-mood="atento">Atento</button><button data-mood="curioso">Curioso</button><button data-mood="feliz">Feliz</button><button data-mood="surpreso">Surpreso</button><button data-mood="pensando">Pensando</button><button data-mood="piscadinha">Piscadinha</button><button data-mood="serio">Sério</button></div>
<button class="wide" data-mood="auto">Voltar às expressões livres</button><p id="state" role="status">Escolha uma expressão. Ela permanece por 8 segundos e depois os olhos voltam a explorar.</p></div>
<div class="card"><button class="wide" id="return">Voltar ao menu Botizin</button><p>O botão físico esquerdo também retorna ao menu.</p><small>Esta etapa controla expressões. Voz e integração com GPT serão etapas seguintes.</small></div>
<script>
const KEY='__SESSION_KEY__';let busy=false,lastId=0;
const $=id=>document.getElementById(id),buttons=[...document.querySelectorAll('button')];
function locked(on){busy=on;buttons.forEach(b=>b.disabled=on)}
async function request(path,options={}){const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),4000);try{const r=await fetch(path,{...options,signal:abort.signal,cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Falha '+r.status);return d}finally{clearTimeout(timer)}}
async function status(){if(busy||document.hidden)return;const start=performance.now();try{const d=await request('/api/status');$('connection').textContent='WROOM conectada • '+d.version;$('metrics').textContent='Resposta local: '+Math.round(performance.now()-start)+' ms\nExpressão: '+d.expression+' • Quadros: '+d.frames+'\nMemória livre: '+Math.round(d.free_heap/1024)+' KB';if(lastId&&d.applied_id===lastId){$('state').textContent='Expressão aplicada na animação: '+d.expression;lastId=0}}catch(e){$('connection').textContent='Sem resposta da placa';$('metrics').textContent='Confira o Wi-Fi e se A22 Expresso está aberto.'}}
async function command(mood){if(busy)return;locked(true);const start=performance.now();try{const d=await request('/api/expression',{method:'POST',headers:{'X-Botizin-Key':KEY,'Content-Type':'application/x-www-form-urlencoded'},body:'expression='+encodeURIComponent(mood)});lastId=d.command_id;$('state').textContent='Comando recebido em '+Math.round(performance.now()-start)+' ms; aguardando a animação.'}catch(e){$('state').textContent=e.message+' — se você reiniciou a placa, recarregue esta página.'}finally{locked(false);status()}}
buttons.filter(b=>b.dataset.mood).forEach(b=>b.onclick=()=>command(b.dataset.mood));
$('return').onclick=async()=>{if(busy||!confirm('Voltar ao menu Botizin?'))return;locked(true);try{await request('/api/return',{method:'POST',headers:{'X-Botizin-Key':KEY}});$('state').textContent='Voltando ao menu. Use /status para conferir após o reinício.';clearInterval(poll)}catch(e){$('state').textContent=e.message;locked(false)}};
const poll=setInterval(status,2000);status();document.addEventListener('visibilitychange',()=>{if(!document.hidden)status()});
</script></main></body></html>)HTML";
