// Server epoch anchored to monotonic elapsed time; browser wall clock is never trusted.
function labMono(){return performance.now();}
function labNow(){var c=self.labClock;return c&&labMono()-c.at<120000?c.epoch+labMono()-c.at:NaN;}
function labRecent(ts){var age=labNow()-Number(ts);return isFinite(age)&&age>=-2000&&age<180000;}
function labClockStart(){
 self.labClock=null;
 function sync(){
  if(self.labClockPending)return;
  self.labClockPending=true;var start=labMono();
  try{self.labClockSubscription=self.ctx.http.get('/api/dashboard/serverTime').subscribe({
   next:function(epoch){var end=labMono();self.labClockPending=false;
    if(typeof epoch==='number'&&isFinite(epoch)&&epoch>0&&end-start<=10000){
     // Upper-bound age by adding full round-trip time; never make old data look newer.
     self.labClock={epoch:epoch+end-start,at:end};
    }
    if(self.root)self.onDataUpdated();
   },error:function(){self.labClockPending=false;if(self.root)self.onDataUpdated();}
  });}catch(e){self.labClockPending=false;}
 }
 sync();self.labClockTimer=setInterval(sync,60000);
}
function labClockStop(){clearInterval(self.labClockTimer);if(self.labClockSubscription)self.labClockSubscription.unsubscribe();self.labClock=null;}

self.onInit=function(){self.root=self.ctx.$container[0];self.busy=false;self.candidate=null;self.v={};self.buttons={};['check','status','confirm','cancel'].forEach(function(a){var b=self.root.querySelector('[data-action="'+a+'"]');self.buttons[a]=b;b.onclick=function(){send(a);};});self.timer=setInterval(ready,1000);labClockStart();self.onDataUpdated();};
function text(k,v){var e=self.root.querySelector('[data-field="'+k+'"]');if(e)e.textContent=v;}
self.onDataUpdated=function(){self.v={};(self.ctx.data||[]).forEach(function(r){if(r.data&&r.data.length){var p=r.data[r.data.length-1];self.v[r.dataKey.name]={value:p[1],ts:Number(p[0])};}});if(self.install){var v=self.v;if(v.firmware_version&&String(v.firmware_version.value)===self.install.version&&v.firmware_version.ts>=self.install.started&&v.ota_state&&String(v.ota_state.value)==='VALID'&&v.boot_id&&String(v.boot_id.value)!==self.install.boot&&v.origin&&v.origin.value==='ESP32_REAL'&&v.simulated&&String(v.simulated.value)==='false'){text('result','Nova versão confirmada pela placa: '+self.install.version);text('details','Boot: '+v.boot_id.value+'\nEstado OTA: VALID\nAutomático continua ligado.');self.install=null;}}ready();};
function ready(){if(!self.root)return;var v=self.v;self.ready=v.firmware_version&&['0.0.6','0.0.7','0.0.8'].indexOf(String(v.firmware_version.value))>=0&&labRecent(v.firmware_version.ts)&&v.origin&&v.origin.value==='ESP32_REAL'&&v.simulated&&String(v.simulated.value)==='false';Object.keys(self.buttons).forEach(function(k){self.buttons[k].disabled=self.busy||!self.ready;});text('availability',!isFinite(labNow())?'Sincronizando horário: aguarde.':!self.ready?'Botões bloqueados: aguardando relato recente e firmware compatível.':self.busy?'Pedido em andamento: aguarde a resposta da placa.':self.candidate&&labMono()<self.candidate.until?'Instalar disponível: candidata '+self.candidate.version+'. Confira antes de instalar.':'Consulta e resultado disponíveis. Instalar bloqueado: ainda não há candidata válida.');self.buttons.confirm.disabled=self.busy||!self.ready||!self.candidate||labMono()>=self.candidate.until;}
function send(action){if(self.busy||!self.ready)return;if(action==='confirm'&&(!self.candidate||labMono()>=self.candidate.until))return;var elapsedStart=labMono(),start=Math.floor(labNow()),command='ota-'+action+'-'+start+'-'+Math.random().toString(16).slice(2,10),params={command_id:command,issued_at_ms:start};if(action==='confirm'){params.candidate_id=self.candidate.id;params.target_version=self.candidate.version;params.sha256=self.candidate.sha;params.boot_id=self.candidate.boot;}self.busy=true;ready();text('result','Aguardando resposta real da WROOM…');var service=self.ctx.$scope.$injector.get(self.ctx.servicesMap.get('deviceService'));self.subscription=service.sendTwoWayRpcCommand('368826d0-c082-11f1-8cda-091689c2cb7f',{method:'ota_'+action,params:params,timeout:30000,persistent:false}).subscribe({next:function(r){self.busy=false;if(!r||r.origin!=='ESP32_REAL'||r.command_id!==command||!r.boot_id||r.automatic_enabled!==true){self.candidate=null;text('result','Resposta sem correspondência; não confirmado');ready();return;}if(action==='check'&&r.result==='CHECK_ACCEPTED'){self.candidate=null;text('result','Consulta aceita. Aguarde alguns segundos e toque em 2. Ver resultado.');}else if(action==='confirm'&&r.result==='INSTALL_ACCEPTED'){self.install={version:self.candidate.version,boot:self.candidate.boot,started:start};self.candidate=null;text('result','Instalação aceita; aguardando novo boot e telemetria VALID.');}else if(action==='cancel'&&r.result==='CANCEL_ACCEPTED'){self.candidate=null;text('result','Pedido cancelado. Automático retoma em até 5 minutos.');}else if(action==='status'&&r.result==='OTA_STATUS'){self.candidate=null;if(r.candidate_ready&&r.candidate_id&&r.target_version&&/^[0-9a-f]{64}$/i.test(r.sha256)&&r.expires_in_seconds>0){self.candidate={id:r.candidate_id,version:r.target_version,sha:r.sha256,boot:r.boot_id,until:elapsedStart+Math.max(0,r.expires_in_seconds*1000)};text('result','Disponível: '+r.target_version+'. Confira e confirme a instalação.');}else{text('result',String(r.internet_status).indexOf('UP_TO_DATE')===0?'Você já está na versão disponível no GitHub.':r.manual_status==='CHECKING'||r.manual_status==='CHECK_QUEUED'?'Consulta em andamento. Aguarde e use Ver resultado.':'Sem candidata pronta. Consulte o GitHub ou veja os detalhes do pedido.');}}else{text('result',r.result);self.candidate=null;}text('details','Placa: '+r.firmware_version+'\nBoot: '+r.boot_id+'\nEstado: '+r.manual_status+'\nOTA: '+r.internet_status+'\nAutomático: ligado'+(r.target_version?'\nCandidata: '+r.target_version+'\nSHA: '+r.sha256:''));ready();},error:function(){self.busy=false;self.candidate=null;text('result','Sem confirmação da placa. Consulte o estado antes de repetir.');ready();}});}
self.onDestroy=function(){labClockStop();clearInterval(self.timer);if(self.subscription)self.subscription.unsubscribe();Object.keys(self.buttons||{}).forEach(function(k){self.buttons[k].onclick=null;});self.root=null;};
self.typeParameters=function(){return{maxDatasources:1,singleEntity:true};};
